#!/bin/sh

# Setup:
  # do a chmod 700 <this file name>

# To run this file:
  # ./<this file name>

# Sample Inputs:
  # Clone url of source repo? -> 
	# https://github.com/sf-wdi-22-23/modules-22.git
  # Source directory (relative path *inside* source repo)? -> 
    # w02-working-with-objects/d3-dawn-forms/
  # Clone url of destination repo? -> 
    # https://github.com/bgveenstra/shared_modules.git
  # Destination directory (relative path *inside* destination repo)? -> 
    # 01-front-end-basics/json-and-html-string/22-23

echo "Standing on the shoulders of giants..."

if [ -d "/" ] ; then
    echo "/ is a directory."
fi

printf "\n  Clone url of source repo? -> "
read SOURCE_REPO
if [ "$SOURCE_REPO" = "" ] ; then
	echo "   no source repo!"
fi
printf "  Source directory (relative path *inside* source repo)? -> "
read SOURCE_DIR
printf "  Clone url of destination repo? -> "
read DESTINATION_REPO
printf "  Destination directory (relative path *inside* destination repo)? -> "
read DESTINATION_DIR

echo "\nremoving old directories"
rm -rf tmp-source tmp-destination

echo "\ncloning $SOURCE_REPO into tmp-source"
git clone $SOURCE_REPO tmp-source
cd tmp-source
git remote rm origin
sleep 2s

if [ -d "./tmp-src" ] ; then
	echo "!!!!!!tmp-srcexists!"
fi

if [ $? = 0 ] ; then
    echo "File exists."
fi